// <auto-generated />
using System;
using EduBook.API_New.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EduBook.API_New.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260521015049_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EduBook.API_New.Models.Author", b =>
                {
                    b.Property<int>("Author_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Author_Id"));

                    b.Property<int?>("Subscribers")
                        .HasColumnType("int");

                    b.Property<int>("User_id")
                        .HasColumnType("int");

                    b.HasKey("Author_Id");

                    b.HasIndex("User_id");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("EduBook.API_New.Models.Comment", b =>
                {
                    b.Property<int>("Comment_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Comment_Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Material_id")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_id")
                        .HasColumnType("int");

                    b.HasKey("Comment_Id");

                    b.HasIndex("Material_id");

                    b.HasIndex("User_id");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("EduBook.API_New.Models.Material", b =>
                {
                    b.Property<int>("Material_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Material_Id"));

                    b.Property<int>("Author_id")
                        .HasColumnType("int");

                    b.Property<int?>("Comments")
                        .HasColumnType("int");

                    b.Property<string>("Discipline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Likes")
                        .HasColumnType("int");

                    b.Property<string>("Material_title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("link_file")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Material_Id");

                    b.HasIndex("Author_id");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("EduBook.API_New.Models.Roles", b =>
                {
                    b.Property<int>("Role_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Role_Id"));

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Role_Id");

                    b.ToTable("Rols");

                    b.HasData(
                        new
                        {
                            Role_Id = 1,
                            Role = "Admin"
                        },
                        new
                        {
                            Role_Id = 2,
                            Role = "Author"
                        },
                        new
                        {
                            Role_Id = 3,
                            Role = "Student"
                        });
                });

            modelBuilder.Entity("EduBook.API_New.Models.User", b =>
                {
                    b.Property<int>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Favorite_material_id")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("User_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_Id");

                    b.HasIndex("Role_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EduBook.API_New.Models.Author", b =>
                {
                    b.HasOne("EduBook.API_New.Models.User", "User")
                        .WithMany("Authors")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduBook.API_New.Models.Comment", b =>
                {
                    b.HasOne("EduBook.API_New.Models.Material", "Material")
                        .WithMany("CommentsList")
                        .HasForeignKey("Material_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduBook.API_New.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduBook.API_New.Models.Material", b =>
                {
                    b.HasOne("EduBook.API_New.Models.Author", "Author")
                        .WithMany("Materials")
                        .HasForeignKey("Author_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("EduBook.API_New.Models.User", b =>
                {
                    b.HasOne("EduBook.API_New.Models.Roles", "Role")
                        .WithMany("Users")
                        .HasForeignKey("Role_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EduBook.API_New.Models.Author", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("EduBook.API_New.Models.Material", b =>
                {
                    b.Navigation("CommentsList");
                });

            modelBuilder.Entity("EduBook.API_New.Models.Roles", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("EduBook.API_New.Models.User", b =>
                {
                    b.Navigation("Authors");

                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
